# Generated by Django 3.1.5 on 2021-05-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team_kaizen1_kiroku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuki', models.IntegerField(default=4)),
                ('output_kaizenteian', models.IntegerField(default=0)),
                ('output_kingaku', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='team_kaizen2_kiroku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuki', models.IntegerField(default=4)),
                ('output_kaizenteian', models.IntegerField(default=0)),
                ('output_kingaku', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='team_kaizen3_kiroku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuki', models.IntegerField(default=4)),
                ('output_kaizenteian', models.IntegerField(default=0)),
                ('output_kingaku', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='team_kaizen4_kiroku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuki', models.IntegerField(default=4)),
                ('output_kaizenteian', models.IntegerField(default=0)),
                ('output_kingaku', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='team_kaizen5_kiroku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuki', models.IntegerField(default=4)),
                ('output_kaizenteian', models.IntegerField(default=0)),
                ('output_kingaku', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='team_kaizen6_kiroku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuki', models.IntegerField(default=4)),
                ('output_kaizenteian', models.IntegerField(default=0)),
                ('output_kingaku', models.IntegerField(default=0)),
            ],
        ),
    ]
