# Generated by Django 3.1.5 on 2021-04-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kakutuki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuki', models.IntegerField(default=1)),
                ('seiri_in', models.IntegerField(default=0)),
                ('seiton_in', models.IntegerField(default=0)),
                ('seisou_in', models.IntegerField(default=0)),
                ('seiketu_in', models.IntegerField(default=0)),
                ('situke_in', models.IntegerField(default=0)),
            ],
        ),
    ]
