# Generated by Django 3.1.5 on 2021-04-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='kakutuki_a',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuki', models.IntegerField(default=1)),
                ('seiri_in', models.IntegerField(default=0)),
                ('seiton_in', models.IntegerField(default=0)),
                ('seisou_in', models.IntegerField(default=0)),
                ('seiketu_in', models.IntegerField(default=0)),
                ('situke_in', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='kakutuki_b',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuki', models.IntegerField(default=1)),
                ('seiri_in', models.IntegerField(default=0)),
                ('seiton_in', models.IntegerField(default=0)),
                ('seisou_in', models.IntegerField(default=0)),
                ('seiketu_in', models.IntegerField(default=0)),
                ('situke_in', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='kakutuki_c',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuki', models.IntegerField(default=1)),
                ('seiri_in', models.IntegerField(default=0)),
                ('seiton_in', models.IntegerField(default=0)),
                ('seisou_in', models.IntegerField(default=0)),
                ('seiketu_in', models.IntegerField(default=0)),
                ('situke_in', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='kakutuki_d',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuki', models.IntegerField(default=1)),
                ('seiri_in', models.IntegerField(default=0)),
                ('seiton_in', models.IntegerField(default=0)),
                ('seisou_in', models.IntegerField(default=0)),
                ('seiketu_in', models.IntegerField(default=0)),
                ('situke_in', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='kakutuki_e',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuki', models.IntegerField(default=1)),
                ('seiri_in', models.IntegerField(default=0)),
                ('seiton_in', models.IntegerField(default=0)),
                ('seisou_in', models.IntegerField(default=0)),
                ('seiketu_in', models.IntegerField(default=0)),
                ('situke_in', models.IntegerField(default=0)),
            ],
        ),
    ]
