# Generated by Django 3.1.5 on 2021-04-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patapp', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='kakutuki',
            name='total_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kakutuki_a',
            name='total_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kakutuki_b',
            name='total_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kakutuki_c',
            name='total_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kakutuki_d',
            name='total_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kakutuki_e',
            name='total_in',
            field=models.IntegerField(default=0),
        ),
    ]
