# Generated by Django 3.1.5 on 2021-04-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patapp', '0004_auto_20210426_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='goukakuten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kijunten', models.IntegerField(default=85)),
            ],
        ),
    ]
