# Generated by Django 3.1.5 on 2021-04-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patapp', '0005_goukakuten'),
    ]

    operations = [
        migrations.CreateModel(
            name='goukakuten_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kijunten_in', models.IntegerField(default=85)),
            ],
        ),
    ]
